server:
  port: 9000

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/

zuul:
  routes:
    consumer:
      path: /api-consumer/**
      serviceId: consumer-service

ribbon:
  eureka:
    enabled: true
